title: Makskeresana
author: Simona
email: simona.macute@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Makskeresana iesacejiem. Raksts bus par to, ka veiksmigi iesakt jaunu hobiju. Pirmas nepieciesamas lietas.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
